/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Each streaming chunk starts with `data:`, separated by two newline characters `\\n\\n`.
 *
 * @export
 * @interface ChunkCompletionResponse
 */
export interface ChunkCompletionResponse {
}
