/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Metadata } from './metadata';
 /**
 * 
 *
 * @export
 * @interface CompletionResponse
 */
export interface CompletionResponse {

    /**
     * @type {string}
     * @memberof CompletionResponse
     */
    event?: string;

    /**
     * @type {string}
     * @memberof CompletionResponse
     */
    messageId?: string;

    /**
     * @type {string}
     * @memberof CompletionResponse
     */
    conversationId?: string;

    /**
     * @type {string}
     * @memberof CompletionResponse
     */
    mode?: string;

    /**
     * @type {string}
     * @memberof CompletionResponse
     */
    answer?: string;

    /**
     * @type {Metadata}
     * @memberof CompletionResponse
     */
    metadata?: Metadata;

    /**
     * Creation timestamp (UNIX epoch time).
     *
     * @type {number}
     * @memberof CompletionResponse
     */
    createdAt?: number;
}
