/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Conversation
 */
export interface Conversation {

    /**
     * @type {string}
     * @memberof Conversation
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Conversation
     */
    name?: string;

    /**
     * @type {any}
     * @memberof Conversation
     */
    inputs?: any;

    /**
     * @type {string}
     * @memberof Conversation
     */
    status?: string;

    /**
     * @type {number}
     * @memberof Conversation
     */
    createdAt?: number;

    /**
     * @type {number}
     * @memberof Conversation
     */
    updatedAt?: number;
}
