/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {

    /**
     * @type {number}
     * @memberof ErrorResponse
     */
    status?: number;

    /**
     * @type {string}
     * @memberof ErrorResponse
     */
    code?: string;

    /**
     * @type {string}
     * @memberof ErrorResponse
     */
    message?: string;
}
