/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FilesUploadBody
 */
export interface FilesUploadBody {

    /**
     * The file to be uploaded.
     *
     * @type {Blob}
     * @memberof FilesUploadBody
     */
    file: Blob;

    /**
     * User identifier.
     *
     * @type {string}
     * @memberof FilesUploadBody
     */
    user: string;
}
