/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FileInput
 */
export interface FileInput {

    /**
     * Supported file categories.
     *
     * @type {string}
     * @memberof FileInput
     */
    type: FileInputTypeEnum;

    /**
     * Transfer method.
     *
     * @type {string}
     * @memberof FileInput
     */
    transferMethod: FileInputTransferMethodEnum;

    /**
     * Image URL (if `remote_url`).
     *
     * @type {string}
     * @memberof FileInput
     */
    url?: string;

    /**
     * Uploaded file ID obtained via File Upload API (if `local_file`).
     *
     * @type {string}
     * @memberof FileInput
     */
    uploadFileId?: string;

    /**
     * Auto-generate title.
     *
     * @type {boolean}
     * @memberof FileInput
     */
    autoGenerateName?: boolean;
}

/**
 * @export
 * @enum {string}
 */
export enum FileInputTypeEnum {
    Document = 'document',
    Image = 'image',
    Audio = 'audio',
    Video = 'video'
}
/**
 * @export
 * @enum {string}
 */
export enum FileInputTransferMethodEnum {
    RemoteUrl = 'remote_url',
    LocalFile = 'local_file'
}

