/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FileUploadResponse
 */
export interface FileUploadResponse {

    /**
     * @type {string}
     * @memberof FileUploadResponse
     */
    id?: string;

    /**
     * @type {string}
     * @memberof FileUploadResponse
     */
    name?: string;

    /**
     * @type {number}
     * @memberof FileUploadResponse
     */
    size?: number;

    /**
     * @type {string}
     * @memberof FileUploadResponse
     */
    extension?: string;

    /**
     * @type {string}
     * @memberof FileUploadResponse
     */
    mimeType?: string;

    /**
     * @type {string}
     * @memberof FileUploadResponse
     */
    createdBy?: string;

    /**
     * @type {number}
     * @memberof FileUploadResponse
     */
    createdAt?: number;
}
