/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetApplicationParametersResponseFileUpload } from './get-application-parameters-response-file-upload';
import { GetApplicationParametersResponseSuggestedQuestionsAfterAnswer } from './get-application-parameters-response-suggested-questions-after-answer';
import { GetApplicationParametersResponseSystemParameters } from './get-application-parameters-response-system-parameters';
import { UserInputFormFileUpload } from './user-input-form-file-upload';
import { UserInputFormParagraph } from './user-input-form-paragraph';
import { UserInputFormSelect } from './user-input-form-select';
import { UserInputFormTextInput } from './user-input-form-text-input';
 /**
 * 
 *
 * @export
 * @interface GetApplicationParametersResponse
 */
export interface GetApplicationParametersResponse {

    /**
     * @type {string}
     * @memberof GetApplicationParametersResponse
     */
    openingStatement?: string;

    /**
     * @type {Array<string>}
     * @memberof GetApplicationParametersResponse
     */
    suggestedQuestions?: Array<string>;

    /**
     * @type {GetApplicationParametersResponseSuggestedQuestionsAfterAnswer}
     * @memberof GetApplicationParametersResponse
     */
    suggestedQuestionsAfterAnswer?: GetApplicationParametersResponseSuggestedQuestionsAfterAnswer;

    /**
     * @type {GetApplicationParametersResponseSuggestedQuestionsAfterAnswer}
     * @memberof GetApplicationParametersResponse
     */
    speechToText?: GetApplicationParametersResponseSuggestedQuestionsAfterAnswer;

    /**
     * @type {GetApplicationParametersResponseSuggestedQuestionsAfterAnswer}
     * @memberof GetApplicationParametersResponse
     */
    retrieverResource?: GetApplicationParametersResponseSuggestedQuestionsAfterAnswer;

    /**
     * @type {GetApplicationParametersResponseSuggestedQuestionsAfterAnswer}
     * @memberof GetApplicationParametersResponse
     */
    annotationReply?: GetApplicationParametersResponseSuggestedQuestionsAfterAnswer;

    /**
     * @type {Array<UserInputFormParagraph | UserInputFormTextInput | UserInputFormSelect | UserInputFormFileUpload>}
     * @memberof GetApplicationParametersResponse
     */
    userInputForm?: Array<UserInputFormParagraph | UserInputFormTextInput | UserInputFormSelect | UserInputFormFileUpload>;

    /**
     * @type {GetApplicationParametersResponseFileUpload}
     * @memberof GetApplicationParametersResponse
     */
    fileUpload?: GetApplicationParametersResponseFileUpload;

    /**
     * @type {GetApplicationParametersResponseSystemParameters}
     * @memberof GetApplicationParametersResponse
     */
    systemParameters?: GetApplicationParametersResponseSystemParameters;
}
