/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Conversation } from './conversation';
 /**
 * 
 *
 * @export
 * @interface GetConversationsResponse
 */
export interface GetConversationsResponse {

    /**
     * @type {number}
     * @memberof GetConversationsResponse
     */
    limit?: number;

    /**
     * @type {boolean}
     * @memberof GetConversationsResponse
     */
    hasMore?: boolean;

    /**
     * @type {Array<Conversation>}
     * @memberof GetConversationsResponse
     */
    data?: Array<Conversation>;
}
