/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetApplicationInfoResponse
 */
export interface GetApplicationInfoResponse {

    /**
     * @type {string}
     * @memberof GetApplicationInfoResponse
     */
    name?: string;

    /**
     * @type {string}
     * @memberof GetApplicationInfoResponse
     */
    description?: string;

    /**
     * @type {Array<string>}
     * @memberof GetApplicationInfoResponse
     */
    tags?: Array<string>;
}
