/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetApplicationParametersResponseSystemParameters
 */
export interface GetApplicationParametersResponseSystemParameters {

    /**
     * @type {number}
     * @memberof GetApplicationParametersResponseSystemParameters
     */
    fileSizeLimit?: number;

    /**
     * @type {number}
     * @memberof GetApplicationParametersResponseSystemParameters
     */
    imageFileSizeLimit?: number;

    /**
     * @type {number}
     * @memberof GetApplicationParametersResponseSystemParameters
     */
    audioFileSizeLimit?: number;

    /**
     * @type {number}
     * @memberof GetApplicationParametersResponseSystemParameters
     */
    videoFileSizeLimit?: number;
}
