/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetApplicationParametersResponseFileUploadImage
 */
export interface GetApplicationParametersResponseFileUploadImage {

    /**
     * @type {boolean}
     * @memberof GetApplicationParametersResponseFileUploadImage
     */
    enabled?: boolean;

    /**
     * @type {number}
     * @memberof GetApplicationParametersResponseFileUploadImage
     */
    numberLimits?: number;

    /**
     * @type {string}
     * @memberof GetApplicationParametersResponseFileUploadImage
     */
    detail?: string;

    /**
     * @type {Array<string>}
     * @memberof GetApplicationParametersResponseFileUploadImage
     */
    transferMethods?: Array<string>;
}
