/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Message } from './message';
 /**
 * 
 *
 * @export
 * @interface GetConversationHistoryResponse
 */
export interface GetConversationHistoryResponse {

    /**
     * @type {number}
     * @memberof GetConversationHistoryResponse
     */
    limit?: number;

    /**
     * @type {boolean}
     * @memberof GetConversationHistoryResponse
     */
    hasMore?: boolean;

    /**
     * @type {Array<Message>}
     * @memberof GetConversationHistoryResponse
     */
    data?: Array<Message>;
}
