/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MessageFeedback } from './message-feedback';
import { MessageFile } from './message-file';
import { RetrieverResource } from './retriever-resource';
 /**
 * 
 *
 * @export
 * @interface Message
 */
export interface Message {

    /**
     * @type {string}
     * @memberof Message
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Message
     */
    conversationId?: string;

    /**
     * @type {any}
     * @memberof Message
     */
    inputs?: any;

    /**
     * @type {string}
     * @memberof Message
     */
    _query?: string;

    /**
     * @type {string}
     * @memberof Message
     */
    answer?: string;

    /**
     * @type {Array<MessageFile>}
     * @memberof Message
     */
    messageFiles?: Array<MessageFile>;

    /**
     * @type {MessageFeedback}
     * @memberof Message
     */
    feedback?: MessageFeedback;

    /**
     * @type {Array<RetrieverResource>}
     * @memberof Message
     */
    retrieverResources?: Array<RetrieverResource>;

    /**
     * @type {number}
     * @memberof Message
     */
    createdAt?: number;
}
