/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RetrieverResource } from './retriever-resource';
import { Usage } from './usage';
 /**
 * 
 *
 * @export
 * @interface Metadata
 */
export interface Metadata {

    /**
     * @type {Usage}
     * @memberof Metadata
     */
    usage?: Usage;

    /**
     * @type {Array<RetrieverResource>}
     * @memberof Metadata
     */
    retrieverResources?: Array<RetrieverResource>;
}
