/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RetrieverResource
 */
export interface RetrieverResource {

    /**
     * @type {number}
     * @memberof RetrieverResource
     */
    position?: number;

    /**
     * @type {string}
     * @memberof RetrieverResource
     */
    datasetId?: string;

    /**
     * @type {string}
     * @memberof RetrieverResource
     */
    datasetName?: string;

    /**
     * @type {string}
     * @memberof RetrieverResource
     */
    documentId?: string;

    /**
     * @type {string}
     * @memberof RetrieverResource
     */
    documentName?: string;

    /**
     * @type {string}
     * @memberof RetrieverResource
     */
    segmentId?: string;

    /**
     * @type {number}
     * @memberof RetrieverResource
     */
    score?: number;

    /**
     * @type {string}
     * @memberof RetrieverResource
     */
    content?: string;
}
