/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TextToAudioRequest
 */
export interface TextToAudioRequest {

    /**
     * For text messages generated by Dify, pass the generated `message_id` directly. The backend will use it to look up the corresponding content and synthesize the voice information directly. If both `message_id` and `text` are provided, `message_id` takes priority. 
     *
     * @type {string}
     * @memberof TextToAudioRequest
     */
    messageId?: string;

    /**
     * Speech generated content.
     *
     * @type {string}
     * @memberof TextToAudioRequest
     */
    text?: string;

    /**
     * User identifier.
     *
     * @type {string}
     * @memberof TextToAudioRequest
     */
    user: string;
}
