/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Usage
 */
export interface Usage {

    /**
     * @type {number}
     * @memberof Usage
     */
    promptTokens?: number;

    /**
     * @type {string}
     * @memberof Usage
     */
    promptUnitPrice?: string;

    /**
     * @type {string}
     * @memberof Usage
     */
    promptPriceUnit?: string;

    /**
     * @type {string}
     * @memberof Usage
     */
    promptPrice?: string;

    /**
     * @type {number}
     * @memberof Usage
     */
    completionTokens?: number;

    /**
     * @type {string}
     * @memberof Usage
     */
    completionUnitPrice?: string;

    /**
     * @type {string}
     * @memberof Usage
     */
    completionPriceUnit?: string;

    /**
     * @type {string}
     * @memberof Usage
     */
    completionPrice?: string;

    /**
     * @type {number}
     * @memberof Usage
     */
    totalTokens?: number;

    /**
     * @type {string}
     * @memberof Usage
     */
    totalPrice?: string;

    /**
     * @type {string}
     * @memberof Usage
     */
    currency?: string;

    /**
     * @type {number}
     * @memberof Usage
     */
    latency?: number;
}
