/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UserInputFormSelectSelect
 */
export interface UserInputFormSelectSelect {

    /**
     * @type {string}
     * @memberof UserInputFormSelectSelect
     */
    label?: string;

    /**
     * @type {string}
     * @memberof UserInputFormSelectSelect
     */
    variable?: string;

    /**
     * @type {boolean}
     * @memberof UserInputFormSelectSelect
     */
    required?: boolean;

    /**
     * @type {string}
     * @memberof UserInputFormSelectSelect
     */
    _default?: string;

    /**
     * @type {Array<string>}
     * @memberof UserInputFormSelectSelect
     */
    options?: Array<string>;
}
