/* tslint:disable */
/* eslint-disable */
/**
 * Chat Application API
 * API documentation for the Chat Application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetApplicationParametersResponseFileUpload } from './get-application-parameters-response-file-upload';
 /**
 * 
 *
 * @export
 * @interface UserInputFormFileUpload
 */
export interface UserInputFormFileUpload {

    /**
     * @type {GetApplicationParametersResponseFileUpload}
     * @memberof UserInputFormFileUpload
     */
    fileUpload?: GetApplicationParametersResponseFileUpload;
}
